### ISSUE TITLE
Persistence in DB

### ISSUE THREAD

**Issue by AndrewsK30** [paritytrading/parity#103]
Hi, great project by the way, so i have question how can i use database to store the order book? because the order book is save on memory, right?

**Comment by k-vladyslav** [comment]
@AndrewsK30 any updates on that?

**Comment by AndrewsK30** [comment]
@k-vladyslav hey, so we end up using a custom solution with Redis and queue by price, and workers threads to do the matching .

**Comment by anujnetwork** [comment]
How did you implement the redis persistence?
Would you like to share the hooks?

**Comment by anujnetwork** [comment]
I am developing a DB Persistence layer based on EclipseLink JPA

**Comment by jvirtanen** [comment]
Hi @AndrewsK30! As you noted, at the moment everything is purely in memory. In longer term, I have thought about splitting Parity Trading System into Parity POE Gateway, Parity Matching Engine, and Parity PMD Gateway that would communicate e.g. over [Aeron](https://github.com/real-logic/aeron). Then persistence could be achieved via [event sourcing](https://martinfowler.com/eaaDev/EventSourcing.html) on the Parity Matching Engine input queue.
