### ISSUE TITLE
System floors down quantity value

### ISSUE THREAD

**Issue by SachinSPawar** [paritytrading/parity#104]
For eg. if quantity is like 0.1 , system floors it to 0.00 and hence rejects the order.
If quantity is like 1.02 , system floors it to 1.00 and accepts order with value 1.00
Is there any way to speciify precision for quantity value?

**Comment by jvirtanen** [comment]
Hi @SachinSPawar! Note that the trading system operates in terms of the [minimum price and quantity increment](https://github.com/paritytrading/parity/blob/master/libraries/net/doc/POE.md#data-types). Other applications, such as the stock ticker, are then configured to convert between this representation and decimal numbers.

In the [example configuration for the stock ticker](https://github.com/paritytrading/parity/blob/master/applications/ticker/etc/example-udp.conf), the instrument AAPL is configured to display with no decimal digits for quantities and the instrument ETH-BTC is configured to display with 3 decimal digits for quantities.

I hope this helps!
