### ISSUE TITLE
Any Graphical User Interface ( GUI) to make things a little easier would be fantastic 

### ISSUE THREAD

**Issue by developeralgo8888** [paritytrading/parity#108]
Any Graphical User Interface ( GUI) to make things a little easier would fantastic

**Comment by jvirtanen** [comment]
Yes, it would. 🙂 I'm hoping to get around to something like that in the future, likely using the JavaScript libraries to interact with the trading system. In the meantime, you might find an [old prototype](https://github.com/jvirtanen/parity-ticker/) I did with React and Play interesting.
