### ISSUE TITLE
How to decrypt user name

### ISSUE THREAD

**Issue by anujnetwork** [paritytrading/parity#109]
User name in session.java in method loginRequest is retrieved as 3978993080922546208.

But my actual user name in conf file is parity.

How do we retrieve use name

**Comment by jvirtanen** [comment]
Hi @anujnetwork! Internally, the trading system [packs the ASCII string as long](https://github.com/paritytrading/parity/blob/master/applications/system/src/main/java/com/paritytrading/parity/system/Session.java#L100). You can either unpack it later using e.g. [`ASCII#unpackLong()`](https://github.com/paritytrading/foundation/blob/master/src/main/java/com/paritytrading/foundation/ASCII.java#L420) or grab the byte array in `loginRequest` before it gets packed.
