### ISSUE TITLE
Incorrect price in Marketreporter.java        orderEntered.price       = price;

### ISSUE THREAD

**Issue by anujnetwork** [paritytrading/parity#110]
MarketReporter.java in orderEntered method is showing incorrect price in 
        orderEntered.price       = price;

For a price of 100, its printing 10000 with 2 leading Zero

However ticket is showing the correct price

Does it require some unpack?

**Comment by jvirtanen** [comment]
The trading system as well as the native protocols use the minimum price increment, please see e.g. [the PMD protocol specification](https://github.com/paritytrading/parity/blob/master/libraries/net/doc/PMD.md#data-types).

**Comment by anujnetwork** [comment]
It doesn't even look like a minimum price increment.
For the very first order of Quantity 1 and Price as 100, it shows Quantity as 1 and Price as 10000

I am still wondering, how ticker is showing the correct price, which is 100

**Comment by jvirtanen** [comment]
Well, the minimum price increment for that particular instrument appears to be 0.01, right? 🙂

**Comment by anujnetwork** [comment]
Where is the minimum price increment defined?
I am running the default system with AAPL instrument

**Comment by jvirtanen** [comment]
It is defined in the configuration files for the applications.
