### ISSUE TITLE
Just New on here

### ISSUE THREAD

**Issue by FndNur1Labs** [paritytrading/parity#120]
i just wanna ask. can this linked with our coins. example we have our coins and own trade...

then how to do this?

sorry new~im just can made blockchain not trade part.

**Comment by jvirtanen** [comment]
Hi @FndNur1Labs! Parity can give you ideas how to implement the matching engine for an exchange, but it is not (nor it tries to be) a full-fledged implementation of an exchange. You might find [Genesis](https://github.com/jvirtanen/genesis), a simple Parity instance that replicates real-time market data from [Coinbase Pro](https://pro.coinbase.com) in a local environment, an interesting overview of Parity capabilities.

**Comment by FndNur1Labs** [comment]
i just fork and run used that?. ah i see port. this i think rpc wallet port?ok i will try. thank you. yep parity easy used. but last i try not on crypto[this one]. so i go another side. thank you very much
