### ISSUE TITLE
Matching Engine's OrderBook not cleared after order Match event

### ISSUE THREAD

**Issue by SergeC** [paritytrading/parity#122]
Matched order is not removed from Orders collection in ME's Order book `com.paritytrading.parity.match.OrderBook#orders`. As a result, it consumes RAM infinitely. The only way to remove an order from orders collection is to call `cancel` method after full order match (an order with remaining quantity 0). Also, fully matched order can't be republished to ME. Test to reproduce this bug attached. Hope to see fixed version soon.

`com/paritytrading/parity/match/OrderBookTest.java` 

> 

```Java
   @Test
    public void buyRepublish() {
        book.enter(1, Side.SELL, 1000, 100);
        book.enter(2, Side.BUY,  1000, 100);
      //        book.cancel(1,0);//  <- workaround to force clear of Orders collection after Match event
        book.enter(1, Side.SELL, 1000, 100);
        Event ask   = new Add(1, Side.SELL, 1000, 100);
        Event match = new Match(1, 2, Side.BUY, 1000, 100, 0);
        Event ask2   = new Add(1, Side.SELL, 1000, 100);
        assertEquals(asList(ask, match, ask2), events.collect()); // <- expected behavior
    }
```

**Comment by jvirtanen** [comment]
Great catch, @SergeC! I will make a patch.

**Comment by SergeC** [comment]
Thanks for addressing this issue. Can you tag a new version?
