### ISSUE TITLE
How to close any connection with system and client

### ISSUE THREAD

**Issue by imrozoodles** [paritytrading/parity#123]
**What we have ***
We have successfully able to connection between client and system. 
Below is the code from TerminalClient.java(Parity-client)
```
TerminalClient.open(new InetSocketAddress(orderEntryAddress, orderEntryPort),
                orderEntryUsername, orderEntryPassword, instruments).run();



```
How can we close this connection?

Thanks

**Comment by jvirtanen** [comment]
Hi @imrozoodles! The connection will be closed as the terminal client terminates.

**Comment by imrozoodles** [comment]
Hi @jvirtanen , How to close connection code wise without terminal client terminates.
