### ISSUE TITLE
Do not depend on Foundation

### ISSUE THREAD

**Issue by jvirtanen** [paritytrading/parity#129]
One of Parity's dependencies is [Foundation](https://github.com/paritytrading/foundation). It would be nice if Parity didn't have this dependency.

**Comment by khsergvl** [comment]
@jvirtanen will start to work over that next days

**Comment by jvirtanen** [comment]
Sounds good, @khsergvl, and welcome! 🙌 

As @JanStureNielsen has been working on this on the [Nassau](https://github.com/paritytrading/nassau) side and some of the usages of Foundation in Parity are due to the Nassau dependency, I suggest that the initial scope of this work on Parity side would be to just get rid of [`ByteBuffers`](https://github.com/paritytrading/foundation/blob/master/src/main/java/com/paritytrading/foundation/ByteBuffers.java) usage for reading and writing unsigned integers. I think that is enough to drop Foundation as a dependency in the [`parity-net`](https://github.com/paritytrading/parity/tree/master/libraries/net) module.

**Comment by khsergvl** [comment]
@jvirtanen after quick look in, here is modules list that depend on foundation:

- libraries-util
- libraries-net
- applications-client
- applications-fix
- applications-system
- applications-reporter

What do you think about moving needed logic to libraries-util? At least ASCII?

**Comment by jvirtanen** [comment]
Let's remove `ByteBuffers` dependency from `parity-net` for starters. It's mainly the transitive dependencies in libraries that would be nice to get rid of, dependencies of the applications do not matter so much. 🙂

**Comment by khsergvl** [comment]
@jvirtanen could you give me access to push in repository?

**Comment by jvirtanen** [comment]
You have to [fork this repository](https://help.github.com/articles/fork-a-repo/). 🙂

**Comment by khsergvl** [comment]
@jvirtanen Let me know if you need something else over this issue or any others.

**Comment by jvirtanen** [comment]
@khsergvl I'll try to come up with some additional issues in the coming days. 🙂

**Comment by jvirtanen** [comment]
This was implemented in #135.
