### ISSUE TITLE
Cannot login to a TCP connection for market-data

### ISSUE THREAD

**Issue by zbron99** [paritytrading/parity#136]
Running the ticker using the TCP example configuration, it is not possible to login to market-data. Connection refused. I suspect this is because the system config file requires UDP settings for market-data? I want to use the Node.js soupbintcp package to login to Parity's market data, though because the ticker itself cannot connect, of course neither can soupbintcp.

**Comment by jvirtanen** [comment]
Hi @zbron99! Please see https://github.com/jvirtanen/genesis/issues/6 for an explanation. 🙂
