### ISSUE TITLE
Market Orders

### ISSUE THREAD

**Issue by tonymackinnon** [paritytrading/parity#139]
It appears as though Parity only supports limit orders, how much effort would be involved in supporting market orders?

**Comment by burnside** [comment]
It had market order support but was removed back in 2017: https://github.com/paritytrading/parity/commit/01c32b7bac861c5da2a143d11ece1d272be32389

Not sure why, though in our implementation we needed market buys to have an awareness of the quote funds available.

**Comment by jvirtanen** [comment]
As @burnside mentioned, the matching algorithm library had market order support in the beginning but it was never implemented in the trading system application or the order entry network protocol. Eventually it was removed from the matching algorithm library as dead weight.

Parity is was heavily inspired by Nasdaq, and there is usually no market order support on institutional exchanges. Assuming reasonable market liquidity, the outcome of a market order can be achieved by a buy limit order with a high-enough price or a sell limit order with a low-enough price.
