### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by jvirtanen** [paritytrading/parity#16]
Market participants should be able to enter orders using HTTP.

**Comment by jvirtanen** [comment]
It might make more sense to make a WebSocket API instead.

**Comment by jvirtanen** [comment]
The [Coinbase Exchange API](https://docs.exchange.coinbase.com) is worth a look.

**Comment by jvirtanen** [comment]
See #28.

**Comment by xbee** [comment]
I think WAMP(Web Application Messaging Protocol) will be another good choice.  Poloniex is using wamp for it's websocket api. And I have integrate reporter with a wamp client, and it working well.

**Comment by anujnetwork** [comment]
Do we heave any rest support today

**Comment by jvirtanen** [comment]
Closing this as REST and WebSocket APIs are outside the scope of the core project.

Note that there are Node implementations of [POE](https://github.com/paritytrading/node-parity-poe), [PMD](https://github.com/paritytrading/node-parity-pmd), and [PMR](https://github.com/paritytrading/node-parity-pmr). Using them, it would be possible to implement REST and WebSocket gateways in similar fashion as [Parity FIX Gateway](https://github.com/paritytrading/parity/tree/master/applications/fix).
