### ISSUE TITLE
Full market depth

### ISSUE THREAD

**Issue by okour82** [paritytrading/parity#161]
is it possible to get the full market depth from Parity exchange , the terminal shows only best bid/offer

**Comment by jvirtanen** [comment]
Yes, see [the market data protocol specification](https://github.com/paritytrading/parity/blob/master/libraries/net/doc/PMD.md) and [the `parity-ticker` code](https://github.com/paritytrading/parity/blob/master/applications/ticker/src/main/java/com/paritytrading/parity/ticker/MarketDataProcessor.java) that uses [the `parity-book` library](https://github.com/paritytrading/parity/tree/master/libraries/book) for order book reconstruction.
