### ISSUE TITLE
Modify Price - Pending Modify

### ISSUE THREAD

**Issue by okour82** [paritytrading/parity#162]
I have Noticed that the FIX can accept to modify quantity but not the price , please advise 

< 8=FIX.4.2|9=115|35=D|49=parity|56=EXECUTOR|34=71|52=20210607-07:51:01|11=2224|55=AAPL|54=1|60=20210607-07:51:01|38=1000|40=2|44=60|10=221|
> 8=FIX.4.4|9=147|35=8|49=parity|56=parity|34=67|52=20210607-07:51:01.276|37=4|11=2224|17=20210607-07:51:01.276|150=0|39=0|55=AAPL|54=1|38=1000|151=1000|14=0|6=0.00|10=024|
< 8=FIX.4.2|9=122|35=G|49=parity|56=EXECUTOR|34=74|52=20210607-07:52:07|11=2225|55=AAPL|54=2|60=20210607-07:52:07|38=500|40=1|44=61|41=2224|10=050|
> 8=FIX.4.4|9=155|35=8|49=parity|56=parity|34=70|52=20210607-07:52:07.513|37=4|11=2225|41=2224|17=20210607-07:52:07.513|150=E|39=E|55=AAPL|54=1|38=1000|151=1000|14=0|6=0.00|10=171|
> 8=FIX.4.4|9=153|35=8|49=parity|56=parity|34=71|52=20210607-07:52:07.693|37=4|11=2225|41=2224|17=20210607-07:52:07.693|150=5|39=0|55=AAPL|54=1|38=500|151=500|14=0|6=0.00|10=063|
< 8=FIX.4.2|9=122|35=G|49=parity|56=EXECUTOR|34=76|52=20210607-07:52:36|11=2226|55=AAPL|54=2|60=20210607-07:52:36|38=500|40=1|44=62|41=2225|10=059|
> 8=FIX.4.4|9=153|35=8|49=parity|56=parity|34=72|52=20210607-07:52:36.442|37=4|11=2226|41=2225|17=20210607-07:52:36.442|150=E|39=E|55=AAPL|54=1|38=500|151=500|14=0|6=0.00|10=091|

**Comment by jvirtanen** [comment]
Correct, you can use Order Cancel/Replace to [partially cancel an order](https://github.com/paritytrading/parity/blob/master/applications/fix/doc/FIX.md#cancel-order-partially).
