### ISSUE TITLE
Pluggable market data out / multicast / TCP modules

### ISSUE THREAD

**Issue by ghost** [paritytrading/parity#42]
Would be great to have abstract interface which user could code into to create arbitrary market data out protocol (MDP)

**Comment by penberg** [comment]
Indeed, ``MatchingEngine`` could be decoupled from ``MarketDataServer`` and others by introducing interfaces that people can implement.

**Comment by jvirtanen** [comment]
I'm currently thinking of implementing these in terms of the market data protocol. In the future, they could be just another type of a market data gateway. See #43 for details.
