### ISSUE TITLE
Pluggable matching algorithms

### ISSUE THREAD

**Issue by divaykin** [paritytrading/parity#44]
Besides FIFO matching there are various algorithms used on different exchanges. For example "pro-rata" i.e. every order on a best level is filled according to it's relative size vs total size. I.e. if there are two orders for 2500 lots and 500 lots on a level a fill of 100 lots would be allocated as (100_5/6) for a first order and (100_1/6) for a second order. Reminder is typically filled at FIFO.

Anyway, there are a lot of rules out there, would be great to have an abstract interface that fills best level.

**Comment by jvirtanen** [comment]
Thanks, I'll have to look into these in more detail.

**Comment by jvirtanen** [comment]
This is interesting, but unlikely to be implemented any time in the near future. 🙂
