### ISSUE TITLE
Implied matching

### ISSUE THREAD

**Issue by divaykin** [paritytrading/parity#45]
http://www.cmegroup.com/confluence/display/EPICSANDBOX/Implied+Orders

In derivative (and some other i.e. swaps) exchanges there is a concept of implied orders / matching. It's sort of an automatic arbitrage between related contracts (typically of different expiry + spread).

Non trivial to implement but important for trading something other than equity / FX.

**Comment by jvirtanen** [comment]
I'll have to look into this in more detail as well.

**Comment by jvirtanen** [comment]
This looks interesting, but I think it's unfortunately going to be outside the scope of the project, at least for the time being.
