### ISSUE TITLE
Toomany Indirections

### ISSUE THREAD

**Issue by sirinath** [paritytrading/parity#53]
Having to navigate through multiple references can slow things down. Wondering if you are willing to try your https://github.com/ObjectLayout/ObjectLayout to speed up referencing where relevant and avoid object with data structure in object with data structure in object with data structure layout?

**Comment by jvirtanen** [comment]
Yes, I agree. Especially the matching engine and order book reconstruction could be improved quite a bit in this regard.

Thanks for the heads-up on ObjectLayout, I'll have a look at it.

**Comment by jvirtanen** [comment]
Regarding this, I had a look at the NASDAQ order books on one day in 2014. On that day AAPL had the following characteristics:

- maximum number of concurrent orders: 29948
- maximum number of concurrent orders on one price level: 1545
- maximum number of concurrent price levels: 3588

These are something to keep in mind when thinking about the optimal data structures for the matching engine and order book reconstruction.
