### ISSUE TITLE
FIX response when requesting a cancel for filled order

### ISSUE THREAD

**Issue by penberg** [paritytrading/parity#70]
When a cancel request is sent for an order that becomes filled before the order can be cancelled, the sequence should look as follows ([source](http://www.onixs.biz/fix-dictionary/4.4/app_dB.1.c.html)):
- Cancel Request (ClOrdID, OrigOrdID)
- Cancel Reject (ClOrdID, OrigOrdID)
- Execution(OrigOrdID)

However, while testing with my own application, I see an execution report with `ClOrdID` set to the _cancel request_ ID, which seems wrong.

**Comment by jvirtanen** [comment]
Thanks for reporting this!

When the FIX Gateway acknowledges an Order Cancel Request with an Execution Report for the pending cancel, it sets OrigClOrdID(41) to the previous ClOrdID(11) and ClOrdID(11) to the Order Cancel Request's ClOrdID(11). This results in the Execution Report for the fill having the wrong ClOrdID(11).

I think the pending cancel should be also eventually rejected. It seems like that it is not currently done at all. However, I have to check the FIX 4.4. specification on this.

**Comment by jvirtanen** [comment]
@penberg Could you test #76? It should fix this issue at least partly.

**Comment by jvirtanen** [comment]
Fixed by #76.
