### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jvirtanen** [paritytrading/parity#73]
Both Parity Trading System and Parity FIX Gateway should implement logging to help with setting up and debugging. The bare minimum would be to log the configuration at the startup.

**Comment by jheusser** [comment]
Btw also worth thinking whether the Aeron-style logging approach makes sense for Parity https://github.com/real-logic/Aeron/wiki/Monitoring-and-Debugging#debug-logging

**Comment by jvirtanen** [comment]
@jheusser Interesting, I have to take a look at that. Also, I have for some time now been considering using Aeron for inter-process communication within the trading system.

**Comment by jheusser** [comment]
Cool. Aeron+SBE could probably carry parity-net very nicely (see https://github.com/tmontgomery/Amaethon/).

**Comment by jvirtanen** [comment]
SBE looks like the successof of FAST for FIX market data. I think it would be a possible future alternative to the native market data protocol, PMD, in similarly as FIX is an alternative to the native order entry protocol, POE.

For inter-process communication within the trading system I have thought about simply running the native protocols on top of Aeron as they already have simple, fixed binary representations. In case of POE, for example, SoupBinTCP, the underlying transport protocol, would be replaced by Aeron between the FIX gateway and the trading system.
