### ISSUE TITLE
Ticker output is hard to read

### ISSUE THREAD

**Issue by penberg** [paritytrading/parity#93]
The default `parity-ticker` output looks as follows:

```
09:37:57.088 BTC-USD    4619.38      14478   4619.39       5121   4619.39        131
```

The format makes it difficult to:

- Notice when a trade happens because last price is repeated all the time.
- Easily see which side of the order book changed (price and size) and how it changed.

The TAQ format (enabled with `-t` command line option) is better, but it could perhaps use color or something to make it even more readable for humans.

**Comment by jvirtanen** [comment]
Yes, good points. The [TAQ format](https://github.com/paritytrading/parity/blob/master/libraries/file/doc/TAQ.md) is actually intended for machines whereas the default is intended for humans. If the TAQ format is more readable, we certainly have some work on the display format. :wink:

I think the display format could use ANSI codes for fixed layout and highlights.

**Comment by xbee** [comment]
maybe can use json format .
