### ISSUE TITLE
integraion points and format

### ISSUE THREAD

**Issue by solutionjet** [paritytrading/parity#94]
Hi not very familiar with fix and other finance protocol. I have couple questions:

 1. How can I feed orders, and get the published result out the system what basically client and reporter is doing ? In my use case I have to write a process to get them from db and persist the published results back into db.
 2. Wonder why you have different multicast ports and how to retrieve data from each request port? Is there any architecture diagram that could explain all the communication flow better?
 3. Whats the use case for using fix server here?

**Comment by jvirtanen** [comment]
Hi @solutionjet! Here are some answers:

1. You can enter orders to the trading system using either the [**POE**](https://github.com/paritytrading/parity/blob/master/libraries/net/doc/POE.md) protocol or the [**FIX**](https://github.com/paritytrading/parity/blob/master/applications/fix/doc/FIX.md) protocol. Both are TCP-based network protocols, and FIX is an industry standard with many free and commercial implementations.

    The terminal client and stock ticker are simple examples on how to interact with the trading system. The order entry and market data protocols themselves are implemented in the [networking protocols](https://github.com/paritytrading/parity/tree/master/libraries/net) library.

2. The trading system provides two distinct data feeds: **market data** and **market reporting**. The market data protocol contains only anonymous information and is intended for all market participants. In contrast, the market reporting protocol contains identifying information (who entered an order, who bought what, and who sold what) and is intended for post-trade processing systems and market surveillance systems.

    Both data feeds are based on a protocol called [**NASDAQ MoldUDP64 1.00**](http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/moldudp64.pdf), and that protocol defines the request format. There are also multiple implementations of this protocol; the implementation used by Parity is called [Nassau](https://github.com/paritytrading/nassau).

3. As FIX is an industry standard, integrating to an exchange using FIX is usually much easier and faster than using the exchange's native order entry protocol. The downside is that FIX has usually higher latency than native order entry protocols, which are usually based on simple and efficient binary encoding.

You might find [Genesis](https://github.com/jvirtanen/genesis) useful as an example of how the different parts fit together. Also, thank you for the reminder, I'll add an architecture diagram. Finally, please consider joining [the Parity chat](https://gitter.im/paritytrading/chat).
