### ISSUE TITLE
Persistence & Scalability 

### ISSUE THREAD

**Issue by mahieddine** [paritytrading/parity#97]
Hi,
First thank you for this wonderful work, i'm trying out your library but i have two questions :

1 -  Does this library use some persistence mechanisms such as if there is an outage, the orderbook is not lost or is it something that the developer should handle himself? if so what would you recommend ?

2 - And the second question is about scalability, can this orderbook works in a clustered setup ? 

Thank you !

**Comment by jvirtanen** [comment]
Hi @mahieddine, and thank you!

1. At the moment, the order book could be reconstructed based on the [market reporting protocol](https://github.com/paritytrading/parity/blob/master/libraries/net/doc/PMR.md) messages. However, as the order entry server does not implement authentication, there is currently no mechanism to map resting orders to incoming sessions. (The trading system also enforces cancel on disconnect: when a session is terminated, all resting orders for the market participant are cancelled.)

2. Regarding scalability, you could run multiple instances of the trading system, each configured to maintain order books for one or more instruments.

I'm currently looking into distributing the trading system into multiple server applications, which will greatly help to implement things such as persistence, authentication (#30), alternative order entry and market data protocols (#42), and alternative matching algorithms (#44). The current plan is to use [Aeron](https://github.com/real-logic/aeron) as the transport medium and FIX encoded as [SBE](https://github.com/real-logic/simple-binary-encoding) as the application protocol between the server applications that constitute a trading system. I intend to write about these plans shortly in [the blog](https://medium.com/parity-blog) in more detail.
