### ISSUE TITLE
Need guide to used this framework

### ISSUE THREAD

**Issue by krissadewo** [paritytrading/parity#99]
Hi, I have compile this project via maven. Because I'm newbie in trading apps, I don't know how to use this setting in config. In example in parity system.

market-data {
  session             = parity
  multicast-interface = 127.0.0.1
  multicast-group     = 224.0.0.1
  multicast-port      = 5000
  request-address     = 127.0.0.1
  request-port        = 5001
}

market-report {
  session             = parity
  multicast-interface = 127.0.0.1
  multicast-group     = 224.0.0.1
  multicast-port      = 6000
  request-address     = 127.0.0.1
  request-port        = 6001
}

order-entry {
  address = 127.0.0.1
  port    = 4000
}

instruments = [
  AAPL,
  ETH-BTC,
  EUR-USD,
]

Where I can get the market data setting ? Should I have some api from market data ?

Any advice appreciate

**Comment by jvirtanen** [comment]
Hi @krissadewo! I suggest to take a look at [Genesis](https://github.com/jvirtanen/genesis), which is built on Parity and [VirtualBox](https://www.virtualbox.org/) and works a self-contained demonstration of a Parity trading system.

**Comment by krissadewo** [comment]
Ok, thank you for advice
